import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "@/providers";

const ubuntoRegular = localFont({
  src: "./fonts/Ubuntu-Regular.ttf",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntoRegular.className} bg-primary-light flex justify-center items-center h-screen`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
